apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vmto.fullname" . }}-worker
  labels:
    {{- include "vmto.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  {{- if not .Values.worker.hpa.enabled }}
  replicas: {{ .Values.worker.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "vmto.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "vmto.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: worker
          image: {{ include "vmto.image" (dict "global" .Values.global "image" .Values.worker.image "root" .) }}
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "vmto.fullname" . }}-config
          env:
            - name: MockMode
              value: {{ .Values.worker.env.mockMode | quote }}
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
